title: Kirthivasan Pandurangan Neelavathi
logo: /assets/img/Kirthivasan_l.png
description: |
  MSDS Graduate Student <br>

 
    <a href="https://www.linkedin.com/in/kirthivasan-pn/">LinkedIn</a> <br>
    <a href="mailto:kirthivasanp@gmail.com">Contact Me</a> <br>
    <a href="/assets/Kirthivasan_PN_DE_resume.pdf" download>Get My Resume</a> <br>
 
show_downloads: true
theme: jekyll-theme-minimal

